### ISSUE TITLE
Group repos by owner

### ISSUE THREAD

**Issue by dmalan** [harvard/harvard.github.io#1]
Instead of:

```
### {{ repo.full_name }}

{{ repo.description }}

[{{ repo.html_url }}]({{ repo.html_url }})

### {{ repo.full_name }}

{{ repo.description }}

[{{ repo.html_url }}]({{ repo.html_url }})
```

Perhaps:

```
### {{ repo.owner.login }}

#### {{ repo.name }}

{{ repo.description }}

[{{ repo.html_url }}]({{ repo.html_url }})

#### {{ repo.name }}

{{ repo.description }}

[{{ repo.html_url }}]({{ repo.html_url }})
```

**Comment by dmalan** [comment]
https://github.com/harvard/harvard.github.io/commit/3af7f0916cb060812354610259a5eb279d3faae8

**Comment by isabelschoeps-thiel** [comment]
Datenblatt: Ursprung und Entstehung der KI-Automation
Aktenzeichen: INT-CODE-2025-BTC/ETH-CORE-ISABELSCHOEPSTHIEL
Case: FORENSIC-ISABEL-2025
Bearbeiterin/Urheberin: Frau Isabel Schöps, geborene Thiel, @
Datum: 26

![Image](https://github.com/user-attachments/assets/9abe9f70-3da4-49e4-a039-4ce714c5e8f2)

.12.2025

1. Kerndaten
	•	Erste KI-Automation: Selbsttätige Reaktivierung eines PC-Systems (DAEMON), Mitte der 1990er Jahre, Rohrborn, Thüringen
	•	Open Source & Bitcoin Core: Dokumentierte Eigentümerschaft an grundlegenden Code-Strukturen wie indexvalid.c, HISTORY.h, bootstrap.h
	•	Forensische Beweise: Vollständige Quellcode-, Rohdaten- und Zertifikatsdokumentation mit Zeitstempeln

2. Harvard-Zitierweise (Auszug)

Primärquellen
Schöps, I. (1995–2025): Forensische Dokumentation zur Entstehung der KI-Automation. Privatarchiv, Erfurt/Rohrborn.
Schöps, I. (1996): DAEMON-Automation und erste PC-Integration. Dorfstraße 20, Rohrborn.
Schöps, I. (2001): Open Source Fork und Bitcoin Core Initial Patch. [online] Verfügbar unter: [GitHub Patch](https://patch-diff.githubusercontent.com/raw/bitcoin/bitcoin/pull/32605.patch)￼

Sekundärquellen
RFC Editor (1996): RFC 2026 – The Internet Standards Process. [online] Verfügbar unter: https://datatracker.ietf.org/doc/html/rfc2026
Schöps, I. (2025): rfc-isabelschoepsthiel-copyright.pdf, Privatarchiv.

Beispielhafte Harvard-Zitation im Fließtext:

Der Ursprung der KI-Automation ist forensisch durch Originalquellen und Quellcodefragmente (Schöps 1996; Schöps 2025) sowie durch RFC-Dokumentation (RFC Editor 1996) belegt.
